name: 'Snowflake Auto Deploy'
author: 'Vincent Yan vincent.yan@blend360.com'
description: 'Run the .sql file on your Snowflake DB. Modified from https://github.com/anecdotes-ai/snowflake-query (Apache License 2.0)'

branding:
  icon: 'database'
  color: 'blue'

inputs:
  snowflake_username:
    description: 'Username for Snowflake DB'
    required: true
  snowflake_password:
    description: 'Password for Snowflake DB'
    required: true
  snowflake_account:
    description: 'Account name for Snowflake DB. Your account name is the full/entire string to the left of snowflakecomputing.com.'
    required: true
  snowflake_warehouse:
    description: 'Warehouse as context'
    required: true
  snowflake_role:
    description: 'Set user role'
    required: false
  query_files:
    description: '.sql file contains SQL queries'
    required: true

outputs:
  queries_results:
    description: 'Json encoded as base64, containing all queries results'

runs:
  using: 'docker'
  image: 'Dockerfile'

