name: Sanity Tests
on: push

jobs:
  test_deploy:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      # Run Queries
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Qeury Files For Testing
        run: |
          echo "create temporary table test (id int, name string); insert into test values (5, 'hello world' ), (8, 'testing');" > query1.sql
          echo "select * from test;" > query2.sql
          cat query1.sql
          cat query2.sql

      - name: Deploy Queries
        uses: ./
        id: run_queries
        with:
          snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          query_files: |-
            query1.sql
            query2.sql
