name: Sanity Tests
on: push

jobs:
  build_docker_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: vinceyan/snowflake-python-3.10

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: vinceyan/snowflake-python-3.10:latest # ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test_deploy:
    runs-on: ubuntu-latest
    name: Test Deploy
    steps:
      # Run Queries
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Qeury Files For Testing
        run: |
          echo "create temporary table test (id int, name string); insert into test values (5, 'hello world' ), (8, 'testing');" > query1.sql
          echo "select * from test;" > query2.sql
          cat query1.sql
          cat query2.sql

      - name: Deploy Queries
        uses: ./
        id: run_queries
        with:
          snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          query_files: |-
            query1.sql
            query2.sql
